/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StakingRouteImport } from './routes/staking'
import { Route as SparksRouteImport } from './routes/sparks'
import { Route as SimpleStakingRouteImport } from './routes/simple-staking'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaucetRouteImport } from './routes/faucet'
import { Route as DualStakingRouteImport } from './routes/dual-staking'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const StakingRoute = StakingRouteImport.update({
  id: '/staking',
  path: '/staking',
  getParentRoute: () => rootRouteImport,
} as any)
const SparksRoute = SparksRouteImport.update({
  id: '/sparks',
  path: '/sparks',
  getParentRoute: () => rootRouteImport,
} as any)
const SimpleStakingRoute = SimpleStakingRouteImport.update({
  id: '/simple-staking',
  path: '/simple-staking',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FaucetRoute = FaucetRouteImport.update({
  id: '/faucet',
  path: '/faucet',
  getParentRoute: () => rootRouteImport,
} as any)
const DualStakingRoute = DualStakingRouteImport.update({
  id: '/dual-staking',
  path: '/dual-staking',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contracts': typeof ContractsRoute
  '/dashboard': typeof DashboardRoute
  '/dual-staking': typeof DualStakingRoute
  '/faucet': typeof FaucetRoute
  '/features': typeof FeaturesRoute
  '/governance': typeof GovernanceRoute
  '/simple-staking': typeof SimpleStakingRoute
  '/sparks': typeof SparksRoute
  '/staking': typeof StakingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contracts': typeof ContractsRoute
  '/dashboard': typeof DashboardRoute
  '/dual-staking': typeof DualStakingRoute
  '/faucet': typeof FaucetRoute
  '/features': typeof FeaturesRoute
  '/governance': typeof GovernanceRoute
  '/simple-staking': typeof SimpleStakingRoute
  '/sparks': typeof SparksRoute
  '/staking': typeof StakingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contracts': typeof ContractsRoute
  '/dashboard': typeof DashboardRoute
  '/dual-staking': typeof DualStakingRoute
  '/faucet': typeof FaucetRoute
  '/features': typeof FeaturesRoute
  '/governance': typeof GovernanceRoute
  '/simple-staking': typeof SimpleStakingRoute
  '/sparks': typeof SparksRoute
  '/staking': typeof StakingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contracts'
    | '/dashboard'
    | '/dual-staking'
    | '/faucet'
    | '/features'
    | '/governance'
    | '/simple-staking'
    | '/sparks'
    | '/staking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contracts'
    | '/dashboard'
    | '/dual-staking'
    | '/faucet'
    | '/features'
    | '/governance'
    | '/simple-staking'
    | '/sparks'
    | '/staking'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contracts'
    | '/dashboard'
    | '/dual-staking'
    | '/faucet'
    | '/features'
    | '/governance'
    | '/simple-staking'
    | '/sparks'
    | '/staking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContractsRoute: typeof ContractsRoute
  DashboardRoute: typeof DashboardRoute
  DualStakingRoute: typeof DualStakingRoute
  FaucetRoute: typeof FaucetRoute
  FeaturesRoute: typeof FeaturesRoute
  GovernanceRoute: typeof GovernanceRoute
  SimpleStakingRoute: typeof SimpleStakingRoute
  SparksRoute: typeof SparksRoute
  StakingRoute: typeof StakingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staking': {
      id: '/staking'
      path: '/staking'
      fullPath: '/staking'
      preLoaderRoute: typeof StakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sparks': {
      id: '/sparks'
      path: '/sparks'
      fullPath: '/sparks'
      preLoaderRoute: typeof SparksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simple-staking': {
      id: '/simple-staking'
      path: '/simple-staking'
      fullPath: '/simple-staking'
      preLoaderRoute: typeof SimpleStakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faucet': {
      id: '/faucet'
      path: '/faucet'
      fullPath: '/faucet'
      preLoaderRoute: typeof FaucetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dual-staking': {
      id: '/dual-staking'
      path: '/dual-staking'
      fullPath: '/dual-staking'
      preLoaderRoute: typeof DualStakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContractsRoute: ContractsRoute,
  DashboardRoute: DashboardRoute,
  DualStakingRoute: DualStakingRoute,
  FaucetRoute: FaucetRoute,
  FeaturesRoute: FeaturesRoute,
  GovernanceRoute: GovernanceRoute,
  SimpleStakingRoute: SimpleStakingRoute,
  SparksRoute: SparksRoute,
  StakingRoute: StakingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
